# Generated by Django 4.2.4 on 2023-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_bug_developer_changestatus_bugcomment_bug_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='network/static/bug_images/'),
        ),
    ]
