# Generated by Django 4.2.4 on 2023-09-22 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_bug_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigneddeveloper',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
