# Generated by Django 4.2.4 on 2023-09-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_assigneddeveloper_date_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='reporter',
        ),
    ]
