# Generated by Django 4.2.4 on 2023-09-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_bug_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
