# Generated by Django 4.2.4 on 2023-09-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_developer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
